apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp-role-binding
subjects:
- kind: Group
  name: system:serviceaccounts:$DUDEMO_KUBE_NAMESPACE
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: psp-role
  apiGroup: rbac.authorization.k8s.io
