apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: $DUDEMO_KUBE_NAMESPACE-psp
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: "*"
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
spec:
  privileged: false
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - "NET_RAW"
  - "SYS_ADMIN"
  - "SYS_PTRACE"
  - "DAC_OVERRIDE"
  - "NET_ADMIN"
  volumes:
  - "*"
  hostNetwork: true
  hostPorts:
  - min: 0
    max: 65535
  hostIPC: true
  hostPID: true
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
