export DUDEMO_KUBE_USER=dudemo-kube-user
export DUDEMO_KUBE_NAMESPACE=dudemo-namespace

if [ -n "$DUDEMO_SUFFIX" ]; then
	DUDEMO_KUBE_USER="$DUDEMO_KUBE_USER-$DUDEMO_SUFFIX"
	DUDEMO_KUBE_NAMESPACE="$DUDEMO_KUBE_NAMESPACE-$DUDEMO_SUFFIX"
fi
