apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dudemo-role
rules:
- apiGroups: [""]
  resources: [ "services/proxy", "events", "pods", "secrets", "services", "ingresses", "replicationcontrollers", "configmaps", "pods/log", "serviceaccounts", "endpoints"]
  verbs: ["get", "watch", "list", "create", "delete", "patch"]
- apiGroups: ["apps"]
  resources: ["replicasets", "deployments", "daemonsets", "statefulsets", "endpoints", "pods", "services"]
  verbs: ["get", "watch", "list", "create", "delete", "patch"]
- apiGroups: ["batch"]
  resources: ["cronjobs", "jobs"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: ["extensions"]
  resources: ["endpoints", "pods", "services"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["get", "watch", "list", "create", "delete"]
