apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dudemo-role
rules:
- apiGroups: [""]
  resources: ["pods", "secrets", "services", "ingresses", "replicationcontrollers", "configmaps", "pods/log"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: ["apps"]
  resources: ["replicasets", "deployments", "daemonsets", "statefulsets"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: ["batch"]
  resources: ["cronjobs", "jobs"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "watch", "list", "create", "delete"]
